#!/usr/bin/env python3
"""Run the TTG Creative Studio ad workflow from a folder or ZIP.

Engine-first entrypoint:
source ZIP/folder -> editable .ttgstudio.json project -> visual contact sheet -> review report.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
SCRIPTS = ROOT / "scripts"
for path in (SRC, SCRIPTS):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from build_ad_project_from_assets import build_ad_project
from render_ad_project_contact_sheet import render_contact_sheet
from ttg_project_schema import TTGProject


def write_report(project_path: Path, contact_sheet: Path, report_path: Path) -> None:
    project = TTGProject.load(project_path)
    image_layers = [layer for layer in project.layers if layer.type == "image"]
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(
        "# TTG Creative Studio Ad Workflow Report\n\n"
        "This report is generated by the non-UI engine workflow.\n\n"
        "## Outputs\n\n"
        f"- Editable project: `{project_path.name}`\n"
        f"- Contact sheet proof: `{contact_sheet.name}`\n\n"
        "## Project summary\n\n"
        f"- Name: {project.name}\n"
        f"- Type: {project.project_type}\n"
        f"- Canvas: {project.canvas.width}x{project.canvas.height}\n"
        f"- FPS: {project.canvas.fps}\n"
        f"- Duration: {project.canvas.duration:.2f}s\n"
        f"- Assets: {len(project.assets)}\n"
        f"- Scene image layers: {len(image_layers)}\n"
        f"- Total layers: {len(project.layers)}\n"
        f"- Audio markers: {len(project.audio_markers)}\n\n"
        "## Pipeline\n\n"
        "Source package/folder -> asset import -> editable scene project -> proof output.\n",
        encoding="utf-8",
    )


def run_workflow(source: Path, output_dir: Path, title: str) -> tuple[Path, Path, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    project_path = output_dir / "ttg_ad_project.ttgstudio.json"
    contact_sheet = output_dir / "ttg_ad_contact_sheet.jpg"
    report = output_dir / "AD_WORKFLOW_REPORT.md"
    workspace = output_dir / "asset_import_workspace"
    build_ad_project(source, project_path, title, workspace=workspace)
    render_contact_sheet(project_path, contact_sheet)
    write_report(project_path, contact_sheet, report)
    return project_path, contact_sheet, report


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path, help="Asset folder or ZIP, e.g. ad.zip")
    parser.add_argument("--output-dir", type=Path, default=ROOT / "outputs" / "ad_workflow_manual")
    parser.add_argument("--title", default="TTG Events Ad")
    args = parser.parse_args()
    project_path, contact_sheet, report = run_workflow(args.source, args.output_dir, args.title)
    print("TTG ad workflow complete")
    print(f"Project: {project_path}")
    print(f"Contact sheet: {contact_sheet}")
    print(f"Report: {report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
